---
# всю кириллицу переводим в нижний регистр
- - А
  - а
- - Б
  - б
- - В
  - в
- - Г
  - г
- - Д
  - д
- - Е
  - е
- - Ё
  - ё
- - Ж
  - ж
- - З
  - з
- - И
  - и
- - Й
  - й
- - К
  - к
- - Л
  - л
- - М
  - м
- - Н
  - н
- - О
  - о
- - П
  - п
- - Р
  - р
- - С
  - с
- - Т
  - т
- - У
  - у
- - Ф
  - ф
- - Х
  - х
- - Ц
  - ц
- - Ч
  - ч
- - Ш
  - ш
- - Щ
  - щ
- - Ъ
  - ъ
- - Ы
  - ы
- - Ь
  - ь
- - Э
  - э
- - Ю
  - ю
- - Я
  - я
#знаки препинания
- - "\\!"
  - Á
- - "\\?"
  - À
- - "\\,"
  - "="
- - "\\;"
  - "="
- - "\\-"
  - "="
- - "\\:"
  - "="
- - "–"
  - "="
- - "—"
  - "="
- - "§"
  - "="
- - "«"
  - "="
- - "»"
  - "="
- - "№"
  - "="
- - "\\."
  - "-"
- - "…"
  - "-"
#цифры
- - '0'
  - ð
- - '1'
  - ñ
- - '2'
  - ò
- - '3'
  - ó
- - '4'
  - ô
- - '5'
  - õ
- - '6'
  - ö
- - '7'
  - "÷"
- - '8'
  - ø
- - '9'
  - ù
# Двойные гласные
- - аа
  - "~C"
- - ээ
  - "~V"
- - ее
  - "~V"
- - ии
  - "~B"
- - оо
  - "~N"
- - уу
  - "~M"
- - ыы
  - nTnT
# Сочетание ьи
- - ьи
  - ьhG
# Буква е
- - ъе
  - ъnF
- - ье
  - ьhR
- - " е"
  - " hR"
- - ае
  - аhR
- - эе
  - эhR
- - ие
  - иhR
- - ое
  - оhR
- - уе
  - уhR
- - ые
  - ыhR
- - яе
  - яhR
- - ёе
  - ёhR
- - юе
  - юhR
# Удвоение. Слоги типа "нни", "бба".
- - бба
  - 'w#:'
- - ббе
  - 'w$:'
- - ббэ
  - 'w$:'
- - бби
  - 'w%:'
- - ббо
  - 'w^:'
- - ббу
  - 'w&:'
- - ббы
  - w:nT
- - вва
  - 'r#:'
- - вве
  - 'r$:'
- - ввэ
  - 'r$:'
- - вви
  - 'r%:'
- - вво
  - 'r^:'
- - вву
  - 'r&:'
- - ввы
  - r:nT
- - гга
  - 'x#:'
- - гге
  - 'x$:'
- - ггэ
  - 'x$:'
- - гги
  - 'x%:'
- - гго
  - 'x^:'
- - ггу
  - 'x&:'
- - ггы
  - x:nT
- - дда
  - '2#:'
- - дде
  - '2$:'
- - ддэ
  - '2$:'
- - дди
  - '2%:'
- - ддо
  - '2^:'
- - дду
  - '2&:'
- - дды
  - 2:nT
- - жжа
  - 'f#:'
- - жже
  - 'f$:'
- - жжэ
  - 'f$:'
- - жжи
  - 'f%:'
- - жжо
  - 'f^:'
- - жжу
  - 'f&:'
- - жжы
  - f:nT
- - зза
  - ",D;"
- - ззе
  - ",R;"
- - ззэ
  - ",R;"
- - ззи
  - ",G;"
- - ззо
  - ",Y;"
- - ззу
  - ",J;"
- - ззы
  - ",;nT"
- - ййа
  - hD;
- - ййе
  - hR;
- - ййэ
  - hR;
- - ййи
  - hG;
- - ййо
  - hH;
- - ййу
  - hJ;
- - ййы
  - h;nT
- - кка
  - zD;
- - кке
  - zR;
- - ккэ
  - zR;
- - кки
  - zG;
- - кко
  - zY;
- - кку
  - zJ;
- - ккы
  - z;nT
- - лла
  - j#?
- - лле
  - j$?
- - ллэ
  - j$?
- - лли
  - j%?
- - лло
  - j^?
- - ллу
  - j&?
- - ллы
  - j?nT
- - мма
  - 't#:'
- - мме
  - 't$:'
- - ммэ
  - 't$:'
- - мми
  - 't%:'
- - ммо
  - 't^:'
- - мму
  - 't&:'
- - ммы
  - t:nT
- - нна
  - '5#:'
- - нне
  - '5$:'
- - ннэ
  - '5$:'
- - нни
  - '5%:'
- - нно
  - '5^:'
- - нну
  - '5&:'
- - нны
  - 5:nT
- - ппа
  - qD;
- - ппе
  - qR;
- - ппэ
  - qR;
- - ппи
  - qT;
- - ппо
  - qY;
- - ппу
  - qU;
- - ппы
  - q;nT
- - рра
  - 7D;
- - рре
  - 7R;
- - ррэ
  - 7R;
- - рри
  - 7T;
- - рро
  - 7Y;
- - рру
  - 7J;
- - рры
  - 7;nT
- - сса
  - i;D
- - ссе
  - i;R
- - ссэ
  - i;R
- - сси
  - i;T
- - ссо
  - 'i;Y '
- - ссу
  - i;J
- - ссы
  - i;nT
- - тта
  - 1D;
- - тте
  - 1R;
- - ттэ
  - 1R;
- - тти
  - 1T;
- - тто
  - 1Y;
- - тту
  - 1J;
- - тты
  - 1;nT
- - ффа
  - eD;
- - ффе
  - eF;
- - ффэ
  - eF;
- - ффи
  - eG;
- - ффо
  - eY;
- - ффу
  - eJ;
- - ффы
  - e;nT
- - хха
  - cE;
- - ххе
  - cR;
- - ххэ
  - cR;
- - ххи
  - cT;
- - ххо
  - cY;
- - хху
  - cU;
- - ххы
  - c;nT
- - цца
  - 1E+?
- - цце
  - 1F+?
- - ццэ
  - 1F+?
- - цци
  - 1T+?
- - ццо
  - 1Y+?
- - ццу
  - 1J+?
- - ццы
  - 1+?nT
- - чча
  - aD;
- - чче
  - aF;
- - ччэ
  - aF;
- - ччи
  - aG;
- - ччо
  - aH;
- - ччу
  - aJ;
- - ччы
  - a;nT
- - шша
  - dE;
- - шше
  - dR;
- - шшэ
  - dR;
- - шши
  - dG;
- - шшо
  - dY;
- - шшу
  - dU;
- - шшы
  - d;nT
- - щща
  - AE;
- - щще
  - AR;
- - щщэ
  - AR;
- - щщи
  - AG;
- - щщо
  - AY;
- - щщу
  - AU;
- - щщы
  - A;nT
# Двойные согласные
- - бб
  - 'w:'
- - вв
  - 'r:'
- - гг
  - 'x:'
- - дд
  - '2:'
- - жж
  - 'f:'
- - зз
  - ",;"
- - йй
  - h;
- - кк
  - z;
- - лл
  - j?
- - мм
  - 't:'
- - нн
  - '5:'
- - пп
  - q;
- - рр
  - 7;
- - сс
  - i;
- - тт
  - 1;
- - фф
  - e;
- - хх
  - c;
- - цц
  - 1+?
- - чч
  - a;
- - шш
  - d;
- - щщ
  - A;
# Слоги
- - ба
  - w#
- - бе
  - w$
- - бэ
  - w$
- - би
  - w%
- - бо
  - w^
- - бу
  - w&
- - бы
  - wnT
- - ва
  - r#
- - ве
  - r$
- - вэ
  - r$
- - ви
  - r%
- - во
  - r^
- - ву
  - r&
- - вы
  - rnT
- - га
  - x#
- - ге
  - x$
- - гэ
  - x$
- - ги
  - x%
- - го
  - x^
- - гу
  - x&
- - гы
  - xnT
- - да
  - 2#
- - де
  - 2$
- - дэ
  - 2$
- - ди
  - 2%
- - до
  - 2^
- - ду
  - 2&
- - ды
  - 2nT
- - жа
  - f#
- - же
  - f$
- - жэ
  - f$
- - жи
  - f%
- - жо
  - f^
- - жу
  - f&
- - жы
  - fnT
- - за
  - ",D"
- - зе
  - ",R"
- - зэ
  - ",R"
- - зи
  - ",G"
- - зо
  - ",Y"
- - зу
  - ",J"
- - зы
  - ",nT"
- - йа
  - hD
- - йе
  - hR
- - йэ
  - hR
- - йи
  - hG
- - йо
  - hH
- - йу
  - hJ
- - йы
  - hnT
- - ка
  - zD
- - ке
  - zR
- - кэ
  - zR
- - ки
  - zG
- - ко
  - zY
- - ку
  - zJ
- - кы
  - znT
- - ла
  - j#
- - ле
  - j$
- - лэ
  - j$
- - ли
  - j%
- - ло
  - j^
- - лу
  - j&
- - лы
  - jnT
- - ма
  - t#
- - ме
  - t$
- - мэ
  - t$
- - ми
  - t%
- - мо
  - t^
- - му
  - t&
- - мы
  - tnT
- - на
  - 5#
- - не
  - 5$
- - нэ
  - 5$
- - ни
  - 5%
- - но
  - 5^
- - ну
  - 5&
- - ны
  - 5nT
- - па
  - qD
- - пе
  - qR
- - пэ
  - qR
- - пи
  - qT
- - по
  - qY
- - пу
  - qU
- - пы
  - qnT
- - ра
  - 7D
- - ре
  - 7R
- - рэ
  - 7R
- - ри
  - 7T
- - ро
  - 7Y
- - ру
  - 7J
- - ры
  - 7nT
- - са
  - iD
- - се
  - iR
- - сэ
  - iR
- - си
  - iT
- - со
  - iY
- - су
  - iJ
- - сы
  - inT
- - та
  - 1D
- - те
  - 1R
- - тэ
  - 1R
- - ти
  - 1T
- - то
  - 1Y
- - ту
  - 1J
- - ты
  - 1nT
- - фа
  - eD
- - фе
  - eF
- - фэ
  - eF
- - фи
  - eG
- - фо
  - eY
- - фу
  - eJ
- - фы
  - enT
- - ха
  - cE
- - хе
  - cR
- - хэ
  - cR
- - хи
  - cT
- - хо
  - cY
- - ху
  - cU
- - хы
  - cnT
- - ца
  - 1E+
- - це
  - 1F+
- - цэ
  - 1F+
- - ци
  - 1T+
- - цо
  - 1Y+
- - цу
  - 1J+
- - цы
  - 1+nT
- - ча
  - aD
- - че
  - aF
- - чэ
  - aF
- - чи
  - aG
- - чо
  - aH
- - чу
  - aJ
- - чы
  - anT
- - ша
  - dE
- - ше
  - dR
- - шэ
  - dR
- - ши
  - dG
- - шо
  - dY
- - шу
  - dU
- - шы
  - dnT
- - ща
  - AE
- - ще
  - AR
- - щэ
  - AR
- - щи
  - AG
- - що
  - AY
- - щу
  - AU
- - щы
  - AnT
# Мягкий знак 
- - бь
  - wÌ
- - вь
  - rÌ
- - гь
  - xÌ
- - дь
  - 2Ì
- - жь
  - fÌ
- - зь
  - ",Í"
- - кь
  - zÍ
- - ль
  - j´
- - мь
  - tÌ
- - нь
  - 5Ì
- - пь
  - qÎ
- - рь
  - 7Î
- - сь
  - 8Î
- - ть
  - 1Î
- - фь
  - eÍ
- - хь
  - cÍ
- - ць
  - 1Î+
- - чь
  - aÍ
- - шь
  - dÍ
- - щь
  - AÍ
# Согласные и твёрдый знак
- - б
  - w
- - в
  - r
- - г
  - x
- - д
  - '2'
- - ж
  - f
- - з
  - k
- - й
  - h
- - к
  - z
- - л
  - j
- - м
  - t
- - н
  - '5'
- - п
  - q
- - р
  - '7'
- - с
  - '8'
- - т
  - '1'
- - ф
  - e
- - х
  - c
- - ц
  - 1+
- - ч
  - a
- - ш
  - d
- - щ
  - A
- - ъ
  - n
# Гласные
- - а
  - "`C"
- - э
  - "`V"
- - е
  - "`V"
- - и
  - "`B"
- - о
  - "`N"
- - у
  - "`M"
- - ы
  - nT
- - я
  - hD
- - ё
  - hH
- - ю
  - hJ
